PLUGINOBJECTS = VectorGenerator.o GenericOpenCVPlugin.o ofxsLut.o
PLUGINNAME = VectorGenerator
#RESOURCES = net.sf.openfx.VectorGenerator.png net.sf.openfx.VectorGenerator.svg


TOP_SRCDIR = ..

VPATH += \
$(TOP_SRCDIR)/VectorGenerator

include $(TOP_SRCDIR)/Makefile.master
